"""What the Rust port may ignore, and what Python's calculator claims to model.

Two generated lists, both about the same question: the port's contract is "the same answer
as Python", and deciding by memory which ids Python acts on is how a port acquires a silent
wrong answer.

    uv run python tools/port_coverage.py                   # what the engine reads
    uv run python tools/port_coverage.py --rust            # -> rust/src/inert.rs
    uv run python tools/port_coverage.py --rust-modelled   # -> rust/src/modelled.rs

`inert.rs` is the ids the engine never acts on, found by scanning its source -- so the port
may ignore them. `modelled.rs` is `effects.all_modelled_abilities()` and
`all_modelled_items()`, which `damage._unmodelled` uses to name, on every hit, the ability
or item the calculator does *not* account for. Those notes reach the caller, so a port that
resolved turns correctly and skipped them would quietly shrink what the caller is told.

Regenerate both when the engine learns a new effect.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

#: The files a turn goes through. `names.py`, the priors and the tools are not the engine.
ENGINE_FILES = [
    "resolve.py",
    "damage.py",
    "effects.py",
    "speed.py",
    "moveinfo.py",
    "view.py",
    "battler.py",
    "actions.py",
]

#: Functions whose bodies are inventories rather than behaviour. `all_modelled_abilities`
#: lists every ability the calculator accounts for, most of them precisely because they do
#: nothing to a damage roll -- so a mention there is the opposite of evidence that the
#: engine acts on the id.
INVENTORY_FUNCTIONS = ("all_modelled_abilities", "all_modelled_items")


def strip_inventories(source: str) -> str:
    out = source
    for name in INVENTORY_FUNCTIONS:
        start = out.find(f"def {name}(")
        if start < 0:
            continue
        rest = out[start:]
        end = len(rest)
        for marker in ("\ndef ", "\n@", "\nclass "):
            found = rest.find(marker, 1)
            if 0 < found < end:
                end = found
        out = out[:start] + out[start + end :]
    return out


def engine_text() -> str:
    return "\n".join(
        strip_inventories((ROOT / "src" / "pokeuraou" / name).read_text(encoding="utf-8"))
        for name in ENGINE_FILES
    )


def mentioned(text: str, identifier: str) -> bool:
    """Whether the engine names this id as a string literal."""
    return re.search(rf'["\']{re.escape(identifier)}["\']', text) is not None


def rust_predicate(name: str, values: list[str], doc: str) -> str:
    body = "\n".join(f'            | "{value}"' for value in values)
    body = body.replace("            | ", "        ", 1)
    return f"{doc}\npub fn {name}(id: &str) -> bool {{\n    matches!(\n        id,\n{body}\n    )\n}}\n"


def write_inert(regulation: str) -> None:
    data = json.loads(
        (ROOT / "configs" / "regulations" / f"{regulation}.json").read_text(encoding="utf-8")
    )
    text = engine_text()
    abilities = [e["id"] for e in data["abilities"] if not mentioned(text, e["id"])]
    items = [e["id"] for e in data["items"] if not mentioned(text, e["id"])]
    header = (
        "//! Ids the Python engine never acts on.\n"
        "//!\n"
        "//! The port's contract is \"the same answer as Python\", so an ability or item\n"
        "//! Python never mentions outside its own inventory lists is one this port may\n"
        "//! ignore without diverging. Generated by `tools/port_coverage.py --rust`.\n\n"
    )
    body = (
        header
        + rust_predicate(
            "ability_is_inert", sorted(abilities), "/// Abilities the engine never reads."
        )
        + "\n"
        + rust_predicate("item_is_inert", sorted(items), "/// Items the engine never reads.")
    )
    (ROOT / "rust" / "src" / "inert.rs").write_text(body, encoding="utf-8")
    print(f"inert.rs: {len(abilities)} abilities, {len(items)} items")


def write_modelled(regulation: str) -> None:
    import sys

    sys.path.insert(0, str(ROOT / "src"))
    from pokeuraou.damage import register_mega_stones
    from pokeuraou.effects import all_modelled_abilities, all_modelled_items
    from pokeuraou.regulation import load_regulation
    from pokeuraou.resolve import STATUS_MOVES_FULLY_MODELLED

    reg = load_regulation(regulation)
    register_mega_stones(reg)
    abilities = sorted(all_modelled_abilities())
    items = sorted(all_modelled_items(frozenset(reg.mega_map)))
    status_moves = sorted(STATUS_MOVES_FULLY_MODELLED)
    header = (
        "//! The ids Python's calculator accounts for, and therefore does not report.\n"
        "//!\n"
        "//! `damage._unmodelled` names every ability and item outside these sets, on every\n"
        "//! hit, and the resolver unions those notes into the turn's report. Generated by\n"
        "//! `tools/port_coverage.py --rust-modelled`.\n\n"
    )
    body = (
        header
        + rust_predicate(
            "ability_is_modelled", abilities, "/// `effects.all_modelled_abilities()`."
        )
        + "\n"
        + rust_predicate(
            "item_is_modelled",
            items,
            "/// `effects.all_modelled_items(mega_stones)` for this regulation's stones.",
        )
        + "\n"
        + rust_predicate(
            "status_move_is_fully_modelled",
            status_moves,
            "/// `resolve.STATUS_MOVES_FULLY_MODELLED`: the status moves whose whole effect\n"
            "/// is the declarative fields, so the resolver does not report them.",
        )
    )
    (ROOT / "rust" / "src" / "modelled.rs").write_text(body, encoding="utf-8")
    print(f"modelled.rs: {len(abilities)} abilities, {len(items)} items")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--regulation", default="gen9championsvgc2026regmc")
    ap.add_argument("--rust", action="store_true", help="write rust/src/inert.rs")
    ap.add_argument("--rust-modelled", action="store_true", help="write rust/src/modelled.rs")
    args = ap.parse_args()

    if args.rust:
        write_inert(args.regulation)
        return
    if args.rust_modelled:
        write_modelled(args.regulation)
        return

    data = json.loads(
        (ROOT / "configs" / "regulations" / f"{args.regulation}.json").read_text(
            encoding="utf-8"
        )
    )
    text = engine_text()
    for kind in ("abilities", "items"):
        ids = sorted(entry["id"] for entry in data[kind])
        read = [i for i in ids if mentioned(text, i)]
        print(f"{kind}: {len(read)} read by the engine, {len(ids) - len(read)} inert")
        print("  read:", ", ".join(read))


if __name__ == "__main__":
    main()
