"""Which ability and item ids the Python engine actually reads.

The Rust port's contract is "the same answer as Python", so an ability Python never
mentions is one the port may ignore without diverging -- and one Python *does* read is one
the port must either implement or refuse. Deciding that by memory is how a port acquires a
silent wrong answer, so it is decided by scanning the source instead.

    uv run python tools/port_coverage.py            # the three lists
    uv run python tools/port_coverage.py --rust     # as a Rust match arm

The engine files are the ones a turn goes through: the resolver, the calculator, the effect
tables, the speed layer and the move-specific mechanics. `names.py`, the priors and the
tools are not the engine and are deliberately not scanned.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENGINE_FILES = [
    "resolve.py",
    "damage.py",
    "effects.py",
    "speed.py",
    "moveinfo.py",
    "view.py",
    "battler.py",
    "actions.py",
]


#: Functions whose bodies are inventories rather than behaviour. `all_modelled_abilities`
#: lists every ability the calculator accounts for, most of them precisely because they do
#: nothing to a damage roll -- so a mention there is the opposite of evidence that the
#: engine acts on the id.
INVENTORY_FUNCTIONS = ("all_modelled_abilities", "all_modelled_items")


def strip_inventories(source: str) -> str:
    """Removes the bodies of the functions that merely list ids."""
    out = source
    for name in INVENTORY_FUNCTIONS:
        start = out.find(f"def {name}(")
        if start < 0:
            continue
        # The body runs to the next top-level definition or decorator.
        rest = out[start:]
        end = len(rest)
        for marker in ("\ndef ", "\n@", "\nclass "):
            found = rest.find(marker, 1)
            if 0 < found < end:
                end = found
        out = out[:start] + out[start + end :]
    return out


def engine_text() -> str:
    return "\n".join(
        strip_inventories((ROOT / "src" / "pokeuraou" / name).read_text(encoding="utf-8"))
        for name in ENGINE_FILES
    )


def mentioned(text: str, identifier: str) -> bool:
    """Whether the engine names this id as a string literal."""
    return re.search(rf'["\']{re.escape(identifier)}["\']', text) is not None


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--regulation", default="gen9championsvgc2026regmc")
    ap.add_argument("--rust", action="store_true", help="print a Rust match arm")
    args = ap.parse_args()

    data = json.loads(
        (ROOT / "configs" / "regulations" / f"{args.regulation}.json").read_text(
            encoding="utf-8"
        )
    )
    text = engine_text()

    abilities = sorted(entry["id"] for entry in data["abilities"])
    items = sorted(entry["id"] for entry in data["items"])

    inert_abilities = [a for a in abilities if not mentioned(text, a)]
    read_abilities = [a for a in abilities if mentioned(text, a)]
    inert_items = [i for i in items if not mentioned(text, i)]
    read_items = [i for i in items if mentioned(text, i)]

    if args.rust:
        def arm(name: str, values: list[str]) -> str:
            body = "\n".join(f'            | "{v}"' for v in values)
            return (
                f"/// Ids the Python engine never mentions, so ignoring them cannot diverge\n"
                f"/// from it. Generated by `tools/port_coverage.py --rust`.\n"
                f"pub fn {name}(id: &str) -> bool {{\n"
                f"    matches!(\n        id,\n"
                + body.replace("            | ", "        ", 1)
                + "\n    )\n}\n"
            )

        print(arm("ability_is_inert", inert_abilities))
        print(arm("item_is_inert", inert_items))
        return

    print(f"abilities: {len(read_abilities)} read by the engine, {len(inert_abilities)} inert")
    print("  read:", ", ".join(read_abilities))
    print(f"\nitems: {len(read_items)} read by the engine, {len(inert_items)} inert")
    print("  read:", ", ".join(read_items))


if __name__ == "__main__":
    main()
