"""Japanese names, from Showdown's own text data rather than from a hand-written table.

Output has to be readable in Japanese -- that is how the game presents itself and how every
build article is written, so an English-only tool cannot be checked against the sources it
was built from. The mapping is generated by ``packages/sim-bridge/src/cli/dump-names.js``
out of the pinned vendor commit, for the same reason regulation data is generated: a table
typed by hand goes stale silently, and a stale name is worse than an English one because it
looks authoritative.

The one rule that matters here is **a missing translation is reported, never faked**.
Showdown marks untranslated entries `name: null` and the dump drops them, so this module
falls back to the English name *and* can say how often it had to. :func:`coverage` measures
that against a regulation, which is the number a test asserts: if a rotation adds Pokemon
Showdown has not translated, the tool should say so rather than quietly print English in
the middle of a Japanese line.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from dataclasses import field as dataclasses_field
from functools import cache
from pathlib import Path
from typing import Any

from .regulation import STAT_IDS, Regulation, repo_root, to_id

DEFAULT_LOCALE = "ja"

#: "Mega", "Mega-X", "Mega-Y" as an English forme suffix.
_MEGA_SUFFIX = re.compile(r"^Mega(?:-([XY]))?$")
#: Japanese writes the X/Y mega markers full-width, as Showdown's own メガリザードンＹ does.
_FULLWIDTH = {"X": "Ｘ", "Y": "Ｙ"}


def names_dir() -> Path:
    return repo_root() / "configs" / "names"


class NamesError(FileNotFoundError):
    pass


@dataclass(frozen=True, slots=True)
class Coverage:
    """How much of a regulation the locale actually covers."""

    kind: str
    total: int
    translated: int
    missing: tuple[str, ...]

    @property
    def fraction(self) -> float:
        return self.translated / self.total if self.total else 1.0

    def __str__(self) -> str:
        head = f"{self.kind}: {self.translated}/{self.total} ({self.fraction * 100:.1f}%)"
        if not self.missing:
            return head
        shown = ", ".join(self.missing[:6])
        more = f" +{len(self.missing) - 6}" if len(self.missing) > 6 else ""
        return f"{head} -- untranslated: {shown}{more}"


@dataclass(frozen=True, slots=True)
class Names:
    """Id -> display name, with English as the stated fallback."""

    locale: str
    showdown_commit: str
    #: id -> the pieces Showdown stores: a full ``name``, or a ``base`` plus a ``forme``.
    #: Composition needs the regulation's English forme as the fallback for a suffix
    #: Showdown has not translated, so it happens in :class:`Localiser`, not here.
    species_parts: dict[str, dict[str, str]]
    moves: dict[str, str]
    items: dict[str, str]
    abilities: dict[str, str]
    natures: dict[str, str]
    types: dict[str, str]
    stats: dict[str, str]
    stats_short: dict[str, str]
    statuses: dict[str, str]
    #: Names supplied by ``configs/names/<locale>-extra.json``, merged over the generated
    #: table. Kept separate so :meth:`coverage` can say what came from Showdown and what
    #: was filled in by hand.
    overrides: dict[str, dict[str, str]] = dataclasses_field(default_factory=dict)

    # ------------------------------------------------------------------ lookup --
    # Every lookup takes the English name as the fallback rather than inventing one, and
    # returns it unchanged when the locale has no entry. That keeps a missing translation
    # visible in the output instead of turning it into a wrong Japanese word.

    def species_full_name(self, species_id: str) -> str | None:
        """The complete name when Showdown stores one, else ``None``."""
        key = to_id(species_id)
        override = (self.overrides.get("species") or {}).get(key)
        if override:
            return override
        return (self.species_parts.get(key) or {}).get("name")

    def species_pieces(self, species_id: str) -> dict[str, str]:
        return dict(self.species_parts.get(to_id(species_id)) or {})

    def move_name(self, move_id: str, english: str | None = None) -> str:
        key = to_id(move_id)
        return (
            (self.overrides.get('moves') or {}).get(key)
            or self.moves.get(key)
            or english
            or move_id
        )

    def item_name(self, item_id: str | None, english: str | None = None) -> str:
        if not item_id:
            return "なし" if self.locale == "ja" else "none"
        key = to_id(item_id)
        return (
            (self.overrides.get('items') or {}).get(key)
            or self.items.get(key)
            or english
            or item_id
        )

    def ability_name(self, ability_id: str, english: str | None = None) -> str:
        key = to_id(ability_id)
        return (
            (self.overrides.get('abilities') or {}).get(key)
            or self.abilities.get(key)
            or english
            or ability_id
        )

    def nature_name(self, nature: str) -> str:
        return self.natures.get(to_id(nature)) or nature

    def type_name(self, type_name: str) -> str:
        return self.types.get(to_id(type_name)) or type_name

    def stat_name(self, stat: str, *, short: bool = False) -> str:
        table = self.stats_short if short else self.stats
        return table.get(stat) or stat

    def status_name(self, status: str | None) -> str:
        if not status:
            return "-"
        return self.statuses.get(status) or status

    # ---------------------------------------------------------------- coverage --

    def _base_japanese(self, reg: Regulation, species_id: str) -> str | None:
        """The Japanese base-species name for a forme, from the base's own entry."""
        found = reg.species.get(to_id(species_id))
        if found is None:
            return None
        base_id = to_id(found.base_species)
        for candidate in (species_id, base_id):
            pieces = self.species_pieces(candidate)
            name = pieces.get("base") or pieces.get("name")
            if name:
                return name
        return None

    def coverage(self, reg: Regulation) -> list[Coverage]:
        """Translation coverage over exactly what this regulation can bring.

        Scoped to the regulation on purpose: Showdown has 450 untranslated Pokedex entries,
        almost all of them Gigantamax and cosmetic formes that Champions never sees, so a
        global count would report a problem that does not exist while hiding one that does.
        """
        out: list[Coverage] = []
        species_ids = [s for s, sp in reg.species.items() if sp.team_legal or sp.changes_from]
        # A forme counts as translated when the *base* is, since the composed name is then
        # Japanese with an English suffix -- readable, and never ambiguous.
        species_table = {
            sid: (
                self.species_full_name(sid)
                or self._base_japanese(reg, sid)
                or ""
            )
            for sid in species_ids
        }
        for kind, ids, table in (
            ("species", species_ids, species_table),
            ("moves", list(reg.moves), self.moves),
            ("items", list(reg.items), self.items),
            ("abilities", list(reg.abilities), self.abilities),
            ("natures", list(reg.natures), self.natures),
            ("stats", list(STAT_IDS), self.stats),
        ):
            missing = tuple(sorted(i for i in ids if not table.get(to_id(i))))
            out.append(
                Coverage(kind=kind, total=len(ids), translated=len(ids) - len(missing), missing=missing)
            )
        return out


def _table(raw: dict[str, Any], key: str) -> dict[str, str]:
    return {to_id(k): str(v) for k, v in (raw.get(key) or {}).items() if v}


@cache
def load_names(locale: str = DEFAULT_LOCALE) -> Names:
    """Reads ``configs/names/<locale>.json``, cached for the process."""
    path = names_dir() / f"{locale}.json"
    if not path.exists():
        raise NamesError(
            f"no name table at {path}. Generate it with: "
            "node packages/sim-bridge/dist/cli/dump-names.js"
        )
    raw = json.loads(path.read_text(encoding="utf-8"))
    meta = raw.get("meta") or {}

    # Hand-supplied names live in a separate file so regenerating the dump never discards
    # them, and so coverage can distinguish "Showdown translated it" from "we did".
    extra_path = names_dir() / f"{locale}-extra.json"
    overrides: dict[str, dict[str, str]] = {}
    if extra_path.exists():
        extra = json.loads(extra_path.read_text(encoding="utf-8"))
        for kind in ("species", "moves", "items", "abilities"):
            table = {to_id(k): str(v) for k, v in (extra.get(kind) or {}).items() if v}
            if table:
                overrides[kind] = table

    return Names(
        locale=str(meta.get("locale", locale)),
        showdown_commit=str(meta.get("showdownCommit", "unknown")),
        species_parts={
            to_id(k): {kk: str(vv) for kk, vv in (v or {}).items() if vv}
            for k, v in (raw.get("species") or {}).items()
        },
        moves=_table(raw, "moves"),
        items=_table(raw, "items"),
        abilities=_table(raw, "abilities"),
        natures=_table(raw, "natures"),
        types=_table(raw, "types"),
        # Stat and status keys are already ids ("hp", "spa", "brn") and must not be
        # re-normalised, since to_id would be a no-op at best and lossy at worst.
        stats={k: str(v) for k, v in (raw.get("stats") or {}).items() if v},
        stats_short={k: str(v) for k, v in (raw.get("statsShort") or {}).items() if v},
        statuses={k: str(v) for k, v in (raw.get("statuses") or {}).items() if v},
        overrides=overrides,
    )


def available_locales() -> tuple[str, ...]:
    if not names_dir().exists():
        return ()
    return tuple(sorted(p.stem for p in names_dir().glob("*.json")))


@dataclass(frozen=True, slots=True)
class Localiser:
    """A regulation plus a locale, which is what display code actually needs.

    Holding both together means the English fallback is the *dump's* English name rather
    than a raw id, so an untranslated entry reads as "Sinistcha" and not "sinistcha".
    """

    reg: Regulation
    names: Names

    def species(self, species_id: str) -> str:
        """The species name, composing base and forme the way Showdown's client does.

        Order of preference: a complete translated name; the translated base plus the
        translated forme; the translated base plus the *English* forme; the English name.
        The third case is what makes Lycanroc-Dusk read as "ルガルガン (Dusk)" rather than
        collapsing onto its Midday forme.
        """
        key = to_id(species_id)
        full = self.names.species_full_name(key)
        if full:
            return full

        found = self.reg.species.get(key)
        base_ja = self.names._base_japanese(self.reg, key)
        if base_ja is None:
            return found.name if found else species_id

        forme_ja = self.names.species_pieces(key).get("forme")
        if forme_ja:
            return f"{base_ja}{forme_ja}"
        if found is None or to_id(found.base_species) == key:
            return base_ja

        # Mega formes: Showdown translates the canon ones as whole names ("メガリザードンＹ")
        # but has nothing for the Champions originals. Japanese writes these by prefixing
        # メガ, which is not a guess -- it is what the cited Japanese tournament reports
        # use throughout (メガスコヴィラン, メガユキメノコ, メガフラエッテ, メガカイリュー,
        # メガプテラ). Applying that convention is different from inventing a name; the
        # stones, whose Japanese names do not follow from the base name at all, are left to
        # the override file instead.
        mega = _MEGA_SUFFIX.match(found.name.removeprefix(f"{found.base_species}-"))
        if mega is not None:
            return f"メガ{base_ja}{_FULLWIDTH.get(mega.group(1) or '', '')}"
        # English suffix for the part Showdown has not translated: "Lycanroc-Dusk" minus
        # "Lycanroc-" is "Dusk".
        suffix = found.name
        prefix = f"{found.base_species}-"
        if suffix.startswith(prefix):
            suffix = suffix[len(prefix) :]
        return f"{base_ja} ({suffix})"

    def move(self, move_id: str) -> str:
        found = self.reg.moves.get(to_id(move_id))
        return self.names.move_name(move_id, found.name if found else None)

    def item(self, item_id: str | None) -> str:
        if not item_id:
            return self.names.item_name(None)
        found = self.reg.items.get(to_id(item_id))
        return self.names.item_name(item_id, found.name if found else None)

    def ability(self, ability_id: str) -> str:
        found = self.reg.abilities.get(to_id(ability_id))
        return self.names.ability_name(ability_id, found.name if found else None)

    def nature(self, nature: str) -> str:
        return self.names.nature_name(nature)

    def stat(self, stat: str, *, short: bool = False) -> str:
        return self.names.stat_name(stat, short=short)

    def status(self, status: str | None) -> str:
        return self.names.status_name(status)

    def spread(self, sp: dict[str, int]) -> str:
        """An SP spread in the order the game's own status screen shows it."""
        return "-".join(str(int(sp.get(stat, 0))) for stat in STAT_IDS)


def localiser(reg: Regulation, locale: str | None = DEFAULT_LOCALE) -> Localiser | None:
    """A :class:`Localiser`, or ``None`` when the caller asked for no localisation."""
    if not locale or locale in ("en", "none"):
        return None
    return Localiser(reg=reg, names=load_names(locale))


__all__ = [
    "DEFAULT_LOCALE",
    "Coverage",
    "Localiser",
    "Names",
    "NamesError",
    "available_locales",
    "load_names",
    "localiser",
    "names_dir",
]
